apiVersion: v1
kind: Namespace

metadata:
  name: ns5

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-dep
  namespace: ns5

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello1
  template:
    metadata:
      name: java-webapp
      labels:
        app: hello1
    spec:
      containers:
      - image: kislayk/hello:v2
        name: hello
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 3
          successThreshold: 1
        
        ports:
        - containerPort: 8080
          name: http

---

kind: Service
apiVersion: v1

metadata:
  name: hello-svc
  namespace: ns5

spec:
  selector:
    app: hello1
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: http
