apiVersion: v1
kind: Namespace

metadata:
  name: ns2
---
apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: my-rs
  namespace: ns2

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello1
  template:
    metadata:
      name: java-webapp
      labels:
        app: hello1
    spec:
      containers:
      - image: kislayk/hello-world-java
        name: hello
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: my-rs2
  namespace: ns2

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello2
  template:
    metadata:
      name: java-webapp2
      labels:
        app: hello2
    spec:
      containers:
      - image: kislayk/hello-world-jva:v2
        name: hello2
        ports:
        - containerPort: 8081
          name: http2
---
kind: Service
apiVersion: v1

metadata:
  name: hello-svc
  namespace: ns2

spec:
  selector:
    app: hello1
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: http

---
kind: Service
apiVersion: v1

metadata:
  name: hello-svc2
  namespace: ns2

spec:
  selector:
    app: hello2
  type: LoadBalancer
  ports:
  - port: 8001
    targetPort: http2
---
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: my-ingress
  namespace: ns2

spec:
  rules:
  - host: kishore.arcesium.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-svc
          servicePort: 8000
      - path: /hi
        backend:
          serviceName: hello-svc2
          servicePort: 8001
