apiVersion: v1
kind: Namespace

metadata:
  name: ns6

---

kind: Service
apiVersion: v1

metadata:
  name: hello-svc
  namespace: ns6

spec:
  selector:
    app: hello1
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8080

---

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: my-ss
  namespace: ns6

spec:
  replicas: 4
  serviceName: hello-svc
  selector:
    matchLabels:
      app: hello1
  template:
    metadata:
      name: java-webapp
      labels:
        app: hello1
    spec:
      containers:
      - image: kislayk/hello:v1
        name: hello
        ports:
        - containerPort: 8080

