apiVersion: v1
kind: Namespace

metadata:
  name: ns8
---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: my-gke-vol-rw

spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: kube-test
    fsType: ext4
---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: my-vol-rw
  namespace: ns8

spec:
  resources:
    requests:
      storage: 1Gi 
  accessModes:
  - ReadWriteMany
  storageClassName: ""

---

apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: my-rs
  namespace: ns8

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello1
  template:
    metadata:
      name: java-webapp
      labels:
        app: hello1
    spec:
      containers:
      - image: kislayk/file-reader:v1
        name: hello
        env:
        - name: fpath
          value: /data/file.txt
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: my-volume
          mountPath: /data/
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-vol-rw
---

kind: Service
apiVersion: v1

metadata:
  name: hello-svc
  namespace: ns8

spec:
  selector:
    app: hello1
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: http
